name: Generate artifact attestations

on:
  workflow_call:
    inputs:
      artifact-path:
        required: true
        type: string
      sbom-path:
        required: true
        type: string

jobs:
  create-attestations:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      artifact-metadata: write
    
    steps:
      - name: Generate SBOM attestation
        uses: actions/attest-sbom@4651f806c01d8637787e274ac3bdf724ef169f34
        with:
          subject-path: ${{ inputs.artifact-path }}
          sbom-path: ${{ inputs.sbom-path }}
          push-to-registry: true
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f
        with:
          subject-path: ${{ inputs.artifact-path }}
          push-to-registry: true
